import {mkdir, readFile, writeFile} from 'node:fs/promises';
import {dirname, resolve} from 'node:path';
import {fileURLToPath, pathToFileURL} from 'node:url';

const ROOT = resolve(dirname(fileURLToPath(import.meta.url)), '..');
const SOURCE_ROOT = resolve(ROOT, 'docs/design/art-sources');
const OUTPUT_ROOT = resolve(ROOT, 'trainer/assets/art');
const MANIFEST_PATH = resolve(ROOT, 'src/trainer/ui/art-manifest.js');
const playwrightPath = process.env.PLAYWRIGHT_MODULE ?? 'playwright';
const executablePath = process.env.BROWSER_EXECUTABLE;

const AVATAR_CANVAS = {width: 1086, height: 1448};
const LANDSCAPE_WIDTHS = [480, 960, 1440];
const AVATAR_WIDTHS = [256, 512, 768];

const SOURCES = [
  {key: 'island-beach', file: 'island-beach.png', widths: LANDSCAPE_WIDTHS},
  {key: 'island-journey', file: 'island-journey.png', widths: LANDSCAPE_WIDTHS},
  ...Array.from({length: 4}, (_, index) => ({
    key: `avatar-skin-${index}`, file: `avatar-skin-${index}.png`, widths: AVATAR_WIDTHS,
    canvas: AVATAR_CANVAS, target: [313, 24, 495, 1414],
  })),
  ...Array.from({length: 6}, (_, index) => ({
    key: `avatar-clothing-${index}`, file: `avatar-clothing-${index}.png`, widths: AVATAR_WIDTHS,
    canvas: AVATAR_CANVAS, target: [323, 296, 440, 382],
  })),
  {key: 'avatar-head-cap', file: 'avatar-head-cap.png', widths: AVATAR_WIDTHS, canvas: AVATAR_CANVAS, target: [350, 22, 385, 260]},
  {key: 'avatar-head-sunhat', file: 'avatar-head-sunhat.png', widths: AVATAR_WIDTHS, canvas: AVATAR_CANVAS, target: [306, 12, 474, 292]},
  {key: 'avatar-head-mountainhat', file: 'avatar-head-mountainhat.png', widths: AVATAR_WIDTHS, canvas: AVATAR_CANVAS, target: [370, 8, 345, 270]},
  {key: 'avatar-back-backpack', file: 'avatar-back-backpack.png', widths: AVATAR_WIDTHS, canvas: AVATAR_CANVAS, target: [270, 275, 555, 610]},
  {key: 'avatar-hand-binoculars', file: 'avatar-hand-binoculars.png', widths: AVATAR_WIDTHS, canvas: AVATAR_CANVAS, target: [710, 650, 220, 250]},
  {key: 'avatar-hand-compass', file: 'avatar-hand-compass.png', widths: AVATAR_WIDTHS, canvas: AVATAR_CANVAS, target: [735, 690, 170, 205]},
];

function moduleUrl(value) {
  if (/^[A-Za-z]:[\\/]/u.test(value)) return pathToFileURL(value).href;
  if (value.startsWith('.')) return new URL(value, import.meta.url).href;
  return value;
}

function manifestModule(art) {
  const fallbackUrls = Object.values(art).map(({fallbackUrl}) => fallbackUrl);
  return `// Generated by scripts/build-art.mjs. Do not edit by hand.\n`
    + `export const ART = Object.freeze(${JSON.stringify(art, null, 2)});\n\n`
    + `export const PRECACHE_ART_URLS = Object.freeze(${JSON.stringify(fallbackUrls, null, 2)});\n\n`
    + `export const AVATAR_LAYER_KEYS = Object.freeze({\n`
    + `  skin: Object.freeze(['avatar-skin-0', 'avatar-skin-1', 'avatar-skin-2', 'avatar-skin-3']),\n`
    + `  clothing: Object.freeze(['avatar-clothing-0', 'avatar-clothing-1', 'avatar-clothing-2', 'avatar-clothing-3', 'avatar-clothing-4', 'avatar-clothing-5']),\n`
    + `  head: Object.freeze({cap: 'avatar-head-cap', sunhat: 'avatar-head-sunhat', mountainhat: 'avatar-head-mountainhat'}),\n`
    + `  back: Object.freeze({backpack: 'avatar-back-backpack'}),\n`
    + `  hand: Object.freeze({binoculars: 'avatar-hand-binoculars', compass: 'avatar-hand-compass'}),\n`
    + `});\n`;
}

async function encode(page, sourceBytes, requestedWidth, transform) {
  return page.evaluate(async ({source, requestedWidth, transform}) => {
    const img = new Image();
    img.src = source;
    await img.decode();
    let logicalWidth = img.naturalWidth;
    let logicalHeight = img.naturalHeight;
    const normalized = document.createElement('canvas');
    if (transform?.canvas) {
      logicalWidth = transform.canvas.width;
      logicalHeight = transform.canvas.height;
      normalized.width = logicalWidth;
      normalized.height = logicalHeight;
      const scan = document.createElement('canvas');
      scan.width = img.naturalWidth;
      scan.height = img.naturalHeight;
      const scanContext = scan.getContext('2d', {willReadFrequently: true});
      scanContext.drawImage(img, 0, 0);
      const pixels = scanContext.getImageData(0, 0, scan.width, scan.height).data;
      let minX = scan.width;
      let minY = scan.height;
      let maxX = -1;
      let maxY = -1;
      for (let y = 0; y < scan.height; y += 1) {
        for (let x = 0; x < scan.width; x += 1) {
          if (pixels[(y * scan.width + x) * 4 + 3] < 16) continue;
          minX = Math.min(minX, x);
          minY = Math.min(minY, y);
          maxX = Math.max(maxX, x);
          maxY = Math.max(maxY, y);
        }
      }
      if (maxX < minX || maxY < minY) throw new Error('Transparent source has no visible pixels');
      const sourceWidth = maxX - minX + 1;
      const sourceHeight = maxY - minY + 1;
      const [targetX, targetY, targetWidth, targetHeight] = transform.target;
      const scale = Math.min(targetWidth / sourceWidth, targetHeight / sourceHeight);
      const width = Math.round(sourceWidth * scale);
      const height = Math.round(sourceHeight * scale);
      const x = Math.round(targetX + (targetWidth - width) / 2);
      const y = Math.round(targetY + (targetHeight - height) / 2);
      normalized.getContext('2d').drawImage(img, minX, minY, sourceWidth, sourceHeight, x, y, width, height);
    } else {
      normalized.width = logicalWidth;
      normalized.height = logicalHeight;
      normalized.getContext('2d').drawImage(img, 0, 0);
    }
    const width = Math.min(requestedWidth, logicalWidth);
    const canvas = document.createElement('canvas');
    canvas.width = width;
    canvas.height = Math.round(logicalHeight * width / logicalWidth);
    canvas.getContext('2d').drawImage(normalized, 0, 0, canvas.width, canvas.height);
    const blob = await new Promise((resolveBlob) => canvas.toBlob(resolveBlob, 'image/webp', 0.86));
    if (!blob || blob.type !== 'image/webp') throw new Error('WebP encoding unavailable');
    return {bytes: Array.from(new Uint8Array(await blob.arrayBuffer())), width: canvas.width, height: canvas.height};
  }, {
    source: `data:image/png;base64,${sourceBytes.toString('base64')}`,
    requestedWidth,
    transform: transform.canvas ? {canvas: transform.canvas, target: transform.target} : null,
  });
}

await mkdir(OUTPUT_ROOT, {recursive: true});
const {chromium} = await import(moduleUrl(playwrightPath));
const browser = await chromium.launch({headless: true, ...(executablePath ? {executablePath} : {})});
const page = await browser.newPage();
const art = {};
try {
  for (const source of SOURCES) {
    const bytes = await readFile(resolve(SOURCE_ROOT, source.file));
    const variants = [];
    for (const requestedWidth of source.widths) {
      const result = await encode(page, bytes, requestedWidth, source);
      if (variants.some(({width}) => width === result.width)) continue;
      const filename = `${source.key}-${result.width}.webp`;
      await writeFile(resolve(OUTPUT_ROOT, filename), Uint8Array.from(result.bytes));
      variants.push({width: result.width, url: `../../../trainer/assets/art/${filename}`});
      art[source.key] ??= {width: result.width, height: result.height, variants: [], fallbackUrl: ''};
      art[source.key].width = Math.max(art[source.key].width, result.width);
      art[source.key].height = Math.max(art[source.key].height, result.height);
    }
    art[source.key].variants = variants;
    art[source.key].fallbackUrl = variants[0].url;
  }
} finally {
  await browser.close();
}
await writeFile(MANIFEST_PATH, manifestModule(art), 'utf8');
process.stdout.write(`Built ${Object.keys(art).length} art assets with ${Object.values(art).reduce((sum, asset) => sum + asset.variants.length, 0)} renditions.\n`);
